new_york:
  lang: en
  tz: America/New_York
  city: New York
  trends: US/NY
  lat: 40.7128
  lon: -74.0060
  feeds:
        - https://www.ny1.com/nyc/all-boroughs/rss
        - https://ny1.com/services/contentfeed.nyc%7call-boroughs%7cnews.landing.rss
        - https://gothamist.com/feed
        - https://www.thecity.nyc/feed

valencia:
  lang: es
  tz: Europe/Madrid
  city: Valencia
  trends: ES
  lat: 39.4699
  lon: -0.3763
  feeds:
    - https://www.elperiodic.com/feed/rss_valencia.xml
    - https://www.levante-emv.com/rss/section/4598
    - https://www.lasprovincias.es/rss/2.0/?section=valencia-ciudad


madrid:
  lang: es
  tz: Europe/Madrid
  city: Madrid
  trends: ES
  lat: 40.4168
  lon: -3.7038
  feeds:
    - https://www.20minutos.es/rss/madrid/
    - https://www.elmundo.es/rss/madrid.xml
    - https://www.madridactual.es/rss/ultimas-noticias-para-dvlr
    - https://gacetinmadrid.com/feed/

tokyo:
  lang: ja
  tz: Asia/Tokyo
  city: 東京
  trends: JP
  lat: 35.6895
  lon: 139.6917
  feeds:
    - https://www3.nhk.or.jp/rss/news/cat0.xml
    - https://www.asahi.com/rss/asahi/newsheadlines.rdf
    - https://mainichi.jp/rss/etc/mainichi-flash.rss
    - https://news.livedoor.com/topics/rss/top.xml

ciudad_de_mexico:
  lang: es
  tz: America/Mexico_City
  city: Ciudad de Mexico
  trends: mx
  lat: 19.4326
  lon: -99.1332
  feeds:
    - https://www.informador.mx/rss/ciudad-de-mexico.xml
    - https://www.meganoticias.mx/cdmx/feed
    - https://www.jornada.com.mx/rss/capital.xml

santander:
  lang: es
  tz: Europe/Madrid
  city: Santander
  country: ES
  trends: spain
  lat: 43.4623
  lon: -3.8099
  feeds:
    - https://www.eldiarioalerta.com/rss/santander

oslo:
  lang: no
  tz: Europe/Oslo
  city: Oslo
  country: NO
  lat: 59.9139
  lon: 10.7522
  feeds:
    - https://www.nrk.no/stor-oslo/toppsaker.rss
    - https://www.aftenposten.no/rss/?kat=oslo/

sao_paulo:
  lang: pt
  tz: America/Sao_Paulo
  city: São Paulo
  country: BR
  lat: -23.5505
  lon: -46.6333
  feeds:
    - https://g1.globo.com/dynamo/sao-paulo/rss2.xml

paris:
  lang: fr
  tz: Europe/Paris
  city: Paris
  lat: 48.8566
  lon: 2.3522
  feeds:
    - https://www.bfmtv.com/rss/paris/

barcelona:
  lang: es
  tz: Europe/Madrid
  city: Barcelona
  lat: 41.3851
  lon: 2.1734
  feeds:
    - https://www.elperiodico.com/es/rss/barcelona/rss.xml