new_york:
  lang: en
  tz: America/New_York
  city: New York
  lat: 40.7128
  lon: -74.0060
  feeds:
        - https://www.ny1.com/nyc/all-boroughs/rss
        - https://ny1.com/services/contentfeed.nyc%7call-boroughs%7cnews.landing.rss
        - https://gothamist.com/feed
        - https://www.thecity.nyc/feed

valencia:
  lang: es
  tz: Europe/Madrid
  city: Valencia
  lat: 39.4699
  lon: -0.3763
  feeds:
    - https://www.elperiodic.com/feed/rss_valencia.xml
    - https://www.levante-emv.com/rss/section/4598
    - https://www.elperiodico.com/es/rss/sociedad/rss.xml


madrid:
  lang: es
  tz: Europe/Madrid
  city: Madrid
  trends: ES
  lat: 40.4168
  lon: -3.7038
  feeds:
    - https://www.20minutos.es/rss/madrid/
    - https://www.elmundo.es/rss/madrid.xml
    - https://www.madridactual.es/rss/ultimas-noticias-para-dvlr
    - https://gacetinmadrid.com/feed/