new_york:
  lang: en
  tz: America/New_York
  city: New York
  city_local: New York
  trends: US/NY
  lat: 40.7128
  lon: -74.0060
  feeds:
    - https://www.ny1.com/nyc/all-boroughs/rss
    - https://ny1.com/services/contentfeed.nyc%7call-boroughs%7cnews.landing.rss
    - https://gothamist.com/feed
    - https://www.thecity.nyc/feed

valencia:
  lang: es
  tz: Europe/Madrid
  city: Valencia
  city_local: Valencia
  trends: ES
  lat: 39.4699
  lon: -0.3763
  feeds:
    - https://www.elperiodic.com/feed/rss_valencia.xml
    - https://www.levante-emv.com/rss/section/4598
    - https://www.lasprovincias.es/rss/2.0/?section=valencia-ciudad

madrid:
  lang: es
  tz: Europe/Madrid
  city: Madrid
  city_local: Madrid
  trends: ES
  lat: 40.4168
  lon: -3.7038
  feeds:
    - https://www.20minutos.es/rss/madrid/
    - https://www.elmundo.es/rss/madrid.xml
    - https://www.madridactual.es/rss/ultimas-noticias-para-dvlr
    - https://gacetinmadrid.com/feed/

tokyo:
  lang: ja
  tz: Asia/Tokyo
  city: 東京
  city_local: 東京
  trends: JP
  lat: 35.6895
  lon: 139.6917
  feeds:
    - https://www3.nhk.or.jp/rss/news/cat0.xml
    - https://www.asahi.com/rss/asahi/newsheadlines.rdf
    - https://mainichi.jp/rss/etc/mainichi-flash.rss
    - https://news.livedoor.com/topics/rss/top.xml

ciudad_de_mexico:
  lang: es
  tz: America/Mexico_City
  city: Ciudad de Mexico
  city_local: Ciudad de México
  trends: mx
  lat: 19.4326
  lon: -99.1332
  feeds:
    - https://www.informador.mx/rss/ciudad-de-mexico.xml
    - https://www.meganoticias.mx/cdmx/feed
    - https://www.jornada.com.mx/rss/capital.xml

santander:
  lang: es
  tz: Europe/Madrid
  city: Santander
  city_local: Santander
  country: ES
  trends: spain
  lat: 43.4623
  lon: -3.8099
  feeds:
    - https://www.ifomo.es/rss/santander/ 
    - https://www.ifomo.es/rss/video/santander/

oslo:
  lang: no
  tz: Europe/Oslo
  city: Oslo
  city_local: Oslo
  country: NO
  lat: 59.9139
  lon: 10.7522
  feeds:
    - https://www.nrk.no/stor-oslo/toppsaker.rss

sao_paulo:
  lang: pt
  tz: America/Sao_Paulo
  city: São Paulo
  city_local: São Paulo
  country: BR
  lat: -23.5505
  lon: -46.6333
  feeds:
    - https://crsaopaulo.com.br/feed
    - https://agora.folha.uol.com.br/agora/rss091.xml

paris:
  lang: fr
  tz: Europe/Paris
  city: Paris
  city_local: Paris
  lat: 48.8566
  lon: 2.3522
  feeds:
    - https://www.bfmtv.com/rss/paris/

barcelona:
  lang: es
  tz: Europe/Madrid
  city: Barcelona
  city_local: Barcelona
  lat: 41.3851
  lon: 2.1734
  feeds:
    - https://www.elperiodico.com/es/rss/barcelona/rss.xml

bucharest:
  lang: ro
  tz: Europe/Bucharest
  city: București
  city_local: București
  country: RO
  lat: 44.4268
  lon: 26.1025
  feeds:
    - https://www.stiripesurse.ro/rss/stiri-din-bucuresti.xml

london:
  lang: en
  tz: Europe/London
  city: London
  city_local: London
  country: GB
  lat: 51.5074
  lon: -0.1278
  feeds:
    - www.mylondon.news/news/?service=rss
    - http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/england/london/rss.xml
    - http://www.standard.co.uk/rss


birmingham:
  lang: en
  tz: Europe/London
  city: Birmingham
  city_local: Birmingham
  country: GB
  lat: 52.4862
  lon: -1.8904
  feeds:
    - https://www.birminghammail.co.uk/news/?service=rss
    - https://www.dailymail.co.uk/news/birmingham/index.rss

istanbul:
  lang: tr
  tz: Europe/Istanbul
  city: İstanbul
  city_local: İstanbul
  country: TR
  lat: 41.0082
  lon: 28.9784
  feeds:
    - https://www.dailysabah.com/rss/istanbul.xml
    - https://www.hurriyetdailynews.com/rss/istanbul
  
dhaka:
  lang: bn
  tz: Asia/Dhaka
  city: Dhaka
  city_local: ঢাকা
  country: BD
  lat: 23.8103
  lon: 90.4125
  feeds:
    - https://www.amarbanglabd.com/feeds